FROM alpine

RUN apk update &&   \
  apk add --no-cache   \ 
	fltk fltk-fluid \
	portaudio    \
	libsndfile     \
	sdl \
	lua5.3 \
	fontconfig ttf-dejavu \
	less mc

ENV HOME="/root"
ENV PATH="$HOME/bin:${PATH}"

WORKDIR /root

COPY p4e.tar .

RUN tar -xf p4e.tar && rm p4e.tar


